global:
  scrape_interval: 15s
  evaluation_interval: 30s
  # scrape_timeout is set to the global default (10s).

rule_files:
  - /etc/prometheus/prometheus-rules.yml

scrape_configs:
  - job_name: mqtt2prometheus
    static_configs:
      - targets: ["mqtt2prometheus:9641"]
